baseURL = "https://eGovFramework.github.io/egovframe-docs/"
languageCode = 'kr'
title = '표준프레임워크 개발가이드'
theme = 'krds-theme'
port = 8888

[markup.tableOfContents]
startLevel = 2  # h2부터 시작
endLevel = 3    # h3까지 포함
ordered = false # 순서 없는 목록(ul)으로 표시

[params]
github_repo = 'https://github.com/eGovFramework/egovframe-docs'
github_project_repo = 'https://github.com/eGovFramework/egovframe-docs'
github_branch = 'main'

#프린트 이용시 설정
[outputFormats.Print]
  name = "print"
  baseName = "print"
  mediaType = "text/html"
  isHTML = true
  rel = "alternate"
  notAlternative = false

[outputs]
  home = ["HTML", "RSS", "Print"]
  section = ["HTML", "Print"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# Markdown 내부에 html태그를 보안상의 이유로 필터링하여 적용하지 않는 기능을 해제
# 태그 예시 : <br>, <script>, <iframe>
# 표(table) 안에 <br> 태그 적용을 위해 html태그 필터링 해제
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
