blank_issues_enabled: false
contact_links:
  - name: 문서 작성 가이드 (Documentation Guide)
    url: https://github.com/eGovFramework/egovframe-docs/blob/main/README.md
    about: 문서 작성 방법과 컨트리뷰션 가이드를 먼저 확인해주세요.
  - name: 전자정부 표준프레임워크 (eGovFrame)
    url: https://www.egovframe.go.kr
    about: 프레임워크 전반에 대한 제안는은 공식 사이트를 이용해주세요.
