name: Link Checker

on:
  pull_request:
  push:
    branches: [ contribution, main ]
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress --exclude-all-private --exclude 'localhost' --exclude '127.0.0.1' .
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File (if links are broken)
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Link Check Failed'
          content-filepath: ./lychee/out.md
          labels: |
            bug
            documentation